{
    'name': 'Educare IEP',

    'version': '17.0.2.0.0',
    'category': 'Education',
    'summary': 'IEP Goals & Objectives - SMART Goal Framework',
    'author': 'Educare',
    'depends': ['educare_base', 'educare_student', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequence_data.xml',
        'data/objective_status_cron.xml',
        'data/iep_master_data.xml',
        'reports/iep_plan_report.xml',
        'reports/iep_plan_report_templates.xml',
        'views/iep_objective_graph.xml',
        'views/iep_objective_pivot.xml',
        'views/iep_objective_kanban.xml',
        'views/iep_master_data_views.xml',
        'views/iep_objective_template_library_views.xml',
        'views/iep_plan_views.xml',
        'views/iep_goal_form.xml',
        'views/iep_goal_tree.xml',
        'views/iep_goal_search.xml',
        'views/iep_goal_kanban.xml',
        'views/iep_objective_form.xml',
        'views/iep_objective_tree.xml',
        'views/iep_objective_search.xml',
        'views/inherit_student_views.xml',
        'wizard/goal_quick_wizard_views.xml',
        'wizard/goal_template_select_wizard_views.xml',
        'wizard/objective_quick_wizard_views.xml',
        'wizard/plan_close_wizard_views.xml',
        'wizard/plan_revision_wizard_views.xml',
        'wizard/plan_reject_wizard_views.xml',
        'wizard/objective_discontinue_wizard_views.xml',
        'wizard/goal_discontinue_wizard_views.xml',
        'wizard/objective_template_import_wizard_views.xml',
        'wizard/objective_configure_wizard_views.xml',
        'wizard/plan_cancel_revision_wizard_views.xml',
        'views/iep_actions.xml',
        'views/iep_menu.xml',
        'data/iep_template_seed_data.xml',
        'data/demo_seed.xml',
    ],
    'demo': [
        'data/demo_seed.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}