{
    'name': 'Educare IEP',
    'version': '17.0.1.0.0',
    'category': 'Education',
    'summary': 'IEP Goals & Objectives - SMART Goal Framework',
    'author': 'Educare',
    'depends': ['educare_base', 'educare_student', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequence_data.xml',
        'data/objective_status_cron.xml',
        'data/iep_master_data.xml',
        'views/iep_master_data_views.xml',
        'views/iep_goal_form.xml',
        'views/iep_goal_tree.xml',
        'views/iep_goal_search.xml',
        'views/iep_goal_kanban.xml',
        'views/iep_objective_form.xml',
        'views/iep_objective_tree.xml',
        'views/iep_objective_search.xml',
        'views/iep_actions.xml',
        'views/iep_menu.xml',
        'data/iep_demo_data.xml',
    ],
    'demo': [],
    'installable': True,
    'license': 'LGPL-3',
}