{
    'name': 'Educare Security',
    'version': '17.0.1.0.0',
    'category': 'Education',
    'summary': 'Security infrastructure — User roles, audit trail, access control',
    'author': 'Educare',
    'depends': ['base', 'mail', 'educare_base'],
    'data': [
        'data/sequence_data.xml',
        'security/educare_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/security_profile_demo_data.xml',
        'data/demo_seed.xml',
        'views/user_profile_views.xml',
        'views/audit_log_views.xml',
        'views/menu.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'license': 'LGPL-3',
}