import logging
from odoo import http, fields
from odoo.http import request

_logger = logging.getLogger(__name__)


class NotificationController(http.Controller):
    """REST API for mobile notification center.

    Auth via Odoo session cookie. Mobile sends JSON-RPC envelope:
        { "jsonrpc": "2.0", "method": "call", "params": {...} }
    Odoo unwraps `params` into method kwargs and wraps return value in
    `{ "jsonrpc": "2.0", "result": ... }`.
    """

    # ───── POST /api/notifications/register-token ─────────────────
    @http.route(
        "/api/notifications/register-token",
        type="json",
        auth="user",
        methods=["POST"],
        csrf=False,
    )
    def register_token(
        self, expo_token=None, platform=None, device_name=None, app_version=None, **_
    ):
        """Register or refresh a device's push token for the current user.

        Idempotent — re-calling with same (user, expo_token) updates `last_seen`
        and re-activates the row instead of inserting a duplicate.
        """
        if not expo_token:
            return {"ok": False, "error": "expo_token is required"}

        Token = request.env["educare.device.token"].sudo()
        existing = Token.search(
            [
                ("user_id", "=", request.env.user.id),
                ("expo_token", "=", expo_token),
            ],
            limit=1,
        )
        vals = {
            "platform": platform or False,
            "device_name": device_name or False,
            "app_version": app_version or False,
            "last_seen": fields.Datetime.now(),
            "active": True,
        }
        if existing:
            existing.write(vals)
            token = existing
        else:
            vals["user_id"] = request.env.user.id
            vals["expo_token"] = expo_token
            token = Token.create(vals)
        return {"ok": True, "token_id": token.id}

    # ───── POST /api/notifications/list ───────────────────────────
    @http.route(
        "/api/notifications/list",
        type="json",
        auth="user",
        methods=["POST"],
        csrf=False,
    )
    def list_notifications(self, limit=50, offset=0, only_unread=False, **_):
        """Return notifications of the current user, newest first.

        For chat notifications (`type='new_chat_message'`), additionally
        resolve the counterpart user from the referenced conversation and
        return their avatar + name as `icon_avatar` / `icon_name` so the
        mobile list can render a real-person avatar instead of a generic
        bell icon.
        """
        domain = [("user_id", "=", request.env.user.id)]
        if only_unread:
            domain.append(("is_read", "=", False))

        notifications = request.env["educare.notification"].search(
            domain,
            limit=int(limit),
            offset=int(offset),
            order="create_date desc",
        )

        # Batch-resolve chat counterparts so we don't do N browse() calls.
        # Guarded: educare_chat may not be installed (educare_notification
        # doesn't depend on it; the relationship is the reverse).
        chat_conv_ids = {
            n.ref_id
            for n in notifications
            if n.type == "new_chat_message"
            and n.ref_model == "educare.chat.conversation"
            and n.ref_id
        }
        counterpart_by_conv = {}
        if chat_conv_ids and "educare.chat.conversation" in request.env.registry:
            Conv = request.env["educare.chat.conversation"].sudo()
            convs = Conv.browse(list(chat_conv_ids)).exists()
            for c in convs:
                # `counterpart_user` resolves from the recipient's perspective;
                # notification.user_id IS the recipient. Pass both endpoints
                # and let the closure pick the right one per noti.
                counterpart_by_conv[c.id] = (
                    c.parent_user_id,
                    c.teacher_user_id,
                )

        def chat_icon_payload(n):
            pair = counterpart_by_conv.get(n.ref_id)
            if not pair:
                return None, None
            parent_user, teacher_user = pair
            other = (
                teacher_user
                if parent_user.id == n.user_id.id
                else parent_user
            )
            if not other:
                return None, None
            # Gate on image_1920 — image_128 is auto-generated by Odoo even
            # when the user has not uploaded a real photo, so it can't tell
            # custom from default. Mobile renders initials when avatar is null.
            has_real_avatar = bool(getattr(other, "image_1920", False))
            raw = other.image_128 if has_real_avatar else None
            avatar_uri = None
            if raw:
                if isinstance(raw, bytes):
                    raw = raw.decode()
                avatar_uri = f"data:image/png;base64,{raw}"
            return avatar_uri, (other.name or "")

        items = []
        for n in notifications:
            icon_avatar, icon_name = (None, None)
            if (
                n.type == "new_chat_message"
                and n.ref_model == "educare.chat.conversation"
                and n.ref_id
            ):
                icon_avatar, icon_name = chat_icon_payload(n)
            items.append(
                {
                    "id": n.id,
                    "type": n.type,
                    "title": n.title,
                    "body": n.body,
                    "ref_model": n.ref_model or None,
                    "ref_id": n.ref_id or None,
                    "is_read": n.is_read,
                    "created_at": fields.Datetime.to_string(n.create_date),
                    "icon_avatar": icon_avatar,
                    "icon_name": icon_name,
                }
            )
        return {"items": items}

    # ───── POST /api/notifications/unread-count ───────────────────
    @http.route(
        "/api/notifications/unread-count",
        type="json",
        auth="user",
        methods=["POST"],
        csrf=False,
    )
    def unread_count(self, **_):
        count = request.env["educare.notification"].search_count(
            [
                ("user_id", "=", request.env.user.id),
                ("is_read", "=", False),
            ]
        )
        return {"count": count}

    # ───── POST /api/notifications/mark-read ──────────────────────
    @http.route(
        "/api/notifications/mark-read",
        type="json",
        auth="user",
        methods=["POST"],
        csrf=False,
    )
    def mark_read(self, ids=None, all=False, **_):
        """Mark one or many notifications as read.

        Args:
            ids: list[int] — specific notification ids
            all: bool — if True, mark ALL of user's notifications as read
        """
        Notif = request.env["educare.notification"]
        if all:
            target = Notif.search(
                [
                    ("user_id", "=", request.env.user.id),
                    ("is_read", "=", False),
                ]
            )
        elif ids:
            target = Notif.search(
                [
                    ("id", "in", [int(i) for i in ids]),
                    ("user_id", "=", request.env.user.id),
                ]
            )
        else:
            return {"ok": False, "error": "Provide `ids` or `all=true`"}

        target.action_mark_read()
        return {"ok": True, "marked": len(target)}
