{
    "name": "Educare Session",
    "version": "17.0.1.1.0",
    "category": "Education",
    "summary": "Session management and objective tracking for Educare",
    "author": "Educare",
    "depends": [
        "mail",
        "educare_base",
        "educare_security",
        "educare_student",
        "educare_iep",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/educare_session_rules.xml",
        "data/ir_sequence_data.xml",
        "data/session_demo_data.xml",
        "views/session_cancel_wizard_views.xml",
        "views/session_review_wizard_views.xml",
        "views/session_result_form.xml",
        "views/session_result_tree.xml",
        "views/session_result_search.xml",
        "views/session_log_form.xml",
        "views/session_log_tree.xml",
        "views/session_log_search.xml",
        "views/session_log_calendar.xml",
        "views/session_actions.xml",
        "views/session_menu.xml",
    ],
    "installable": True,
    "license": "LGPL-3",
}
