{
    "name": "Educare Daily Report",
    "version": "17.0.1.0.0",
    "category": "Education",
    "summary": "Daily session reports for parents",
    "author": "Educare Team",
    "license": "LGPL-3",
    "depends": [
        "educare_student",
        "educare_session",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/sequence_data.xml",
        "data/mail_template.xml",
        "wizard/generate_report_wizard_views.xml",
        "views/daily_report_form.xml",
        "views/daily_report_tree.xml",
        "views/daily_report_search.xml",
        "views/daily_report_actions.xml",
        "views/session_log_inherit.xml",
        "views/menu.xml",
    ],
    "demo": [
        "data/report_demo_data.xml",
    ],
    "installable": True,
    "application": False,
}
